// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./server/db/prisma/",
  migrations: {
    path: "server/db/prisma/migrations",
    seed: `tsx server/db/prisma/seed.ts`,
  },
  datasource: {
    url:
      process.env.PRISMA_DATABASE_URL || process.env.NEXT_PUBLIC_DATABASE_URL,
  },
});
