query GetProcesses(
  $filter: ProcessFilterInput
  $pagination: ProcessPaginationInput
) {
  processes(filter: $filter, pagination: $pagination) {
    nodes {
      id
      companyId
      departmentId
      title
      description
      plannedHours
      complexity
      businessImpact
      newness
      isBurningOut
      weight
      status
      createdAt
      updatedAt
      company {
        id
        name
      }
      department {
        id
        name
      }
    }
    totalCount
    pageInfo {
      hasMore
      offset
      limit
      total
    }
  }
}
